// Generated by scripts/build-bos-client-dependency-contract.mjs. Do not edit.
export default {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "bos://contracts/client-dependency/v1/discovered-operation-request",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "contact"
  ],
  "properties": {
    "contact": {
      "$ref": "#/$defs/described_operation"
    },
    "payload": true
  },
  "allOf": [
    {
      "properties": {
        "contact": {
          "properties": {
            "execution": {
              "properties": {
                "method": {
                  "enum": [
                    "GET",
                    "POST",
                    "PUT",
                    "PATCH",
                    "DELETE"
                  ]
                },
                "uri": {
                  "type": "string"
                },
                "context_header": {
                  "const": "X-BOS-Context-Handle"
                },
                "transport": {
                  "type": "null"
                },
                "response": {
                  "$ref": "#/$defs/described_operation/properties/execution/properties/response"
                }
              },
              "required": [
                "method",
                "uri",
                "context_header"
              ]
            }
          },
          "required": [
            "execution"
          ]
        }
      },
      "required": [
        "contact"
      ]
    },
    {
      "if": {
        "properties": {
          "contact": {
            "properties": {
              "execution": {
                "properties": {
                  "method": {
                    "const": "GET"
                  }
                },
                "required": [
                  "method"
                ]
              }
            },
            "required": [
              "execution"
            ]
          }
        },
        "required": [
          "contact"
        ]
      },
      "then": {
        "not": {
          "required": [
            "payload"
          ]
        }
      },
      "else": {
        "required": [
          "payload"
        ]
      }
    }
  ],
  "$defs": {
    "described_operation": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "operation",
        "status",
        "effect",
        "limits",
        "guarantees",
        "execution",
        "input_schema",
        "output_schema",
        "error_contract",
        "sources"
      ],
      "properties": {
        "operation": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"
        },
        "status": {
          "const": "described"
        },
        "effect": {
          "type": "string",
          "minLength": 1
        },
        "limits": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "max_targets",
            "max_results_per_source",
            "pagination_supported",
            "bulk_supported",
            "streaming_supported",
            "maximum_duration_seconds",
            "maximum_fan_out"
          ],
          "properties": {
            "max_targets": {
              "type": [
                "integer",
                "null"
              ],
              "minimum": 1
            },
            "max_results_per_source": {
              "type": [
                "integer",
                "null"
              ],
              "minimum": 1
            },
            "pagination_supported": {
              "type": "boolean"
            },
            "bulk_supported": {
              "type": "boolean"
            },
            "streaming_supported": {
              "type": "boolean"
            },
            "multiple_selectors_per_source": {
              "type": "boolean"
            },
            "maximum_attachment_bytes": {
              "type": "integer",
              "minimum": 1,
              "maximum": 26214400
            },
            "maximum_duration_seconds": {
              "type": "integer",
              "minimum": 1
            },
            "maximum_fan_out": {
              "type": "integer",
              "minimum": 1
            }
          }
        },
        "guarantees": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "read_consistency",
            "per_source_atomicity",
            "cross_source_atomicity",
            "convergence",
            "idempotency"
          ],
          "properties": {
            "read_consistency": {
              "type": "string",
              "minLength": 1
            },
            "per_source_atomicity": {
              "type": "string",
              "minLength": 1
            },
            "cross_source_atomicity": {
              "type": "string",
              "minLength": 1
            },
            "convergence": {
              "type": "string",
              "minLength": 1
            },
            "idempotency": {
              "const": "service_owned"
            }
          }
        },
        "execution": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "method",
            "uri",
            "context_header"
          ],
          "properties": {
            "method": {
              "enum": [
                "GET",
                "POST",
                "PUT",
                "PATCH",
                "DELETE"
              ]
            },
            "uri": {
              "type": "string",
              "maxLength": 4096,
              "pattern": "^/bos/(?!/)(?!.*//)(?!(?:[^/?]+/)*\\.{1,2}(?:/|\\?|$))(?!.*[#\\\\\\u0000-\\u001F\\u007F])(?:[A-Za-z0-9._~!$&'()*+,;=:@{}/?-]|%[0-9A-F]{2})+$"
            },
            "context_header": {
              "const": "X-BOS-Context-Handle"
            },
            "transport": {
              "type": "null"
            },
            "response": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "body",
                "content_type",
                "headers"
              ],
              "properties": {
                "body": {
                  "const": "binary"
                },
                "content_type": {
                  "const": "provider"
                },
                "headers": {
                  "type": "array",
                  "minItems": 6,
                  "maxItems": 6,
                  "uniqueItems": true,
                  "items": {
                    "enum": [
                      "Content-Disposition",
                      "Content-Length",
                      "Content-Type",
                      "Digest",
                      "X-Content-SHA256",
                      "X-Correlation-ID"
                    ]
                  },
                  "allOf": [
                    {
                      "contains": {
                        "const": "Content-Disposition"
                      }
                    },
                    {
                      "contains": {
                        "const": "Content-Length"
                      }
                    },
                    {
                      "contains": {
                        "const": "Content-Type"
                      }
                    },
                    {
                      "contains": {
                        "const": "Digest"
                      }
                    },
                    {
                      "contains": {
                        "const": "X-Content-SHA256"
                      }
                    },
                    {
                      "contains": {
                        "const": "X-Correlation-ID"
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "input_schema": {
          "type": "object",
          "required": [
            "$schema",
            "type",
            "x-bos-fields"
          ],
          "properties": {
            "$schema": {
              "const": "https://json-schema.org/draft/2020-12/schema"
            },
            "type": {
              "const": "object"
            },
            "x-bos-fields": {
              "type": "array"
            }
          }
        },
        "output_schema": {
          "type": "object",
          "required": [
            "$schema",
            "type",
            "x-bos-fields"
          ],
          "properties": {
            "$schema": {
              "const": "https://json-schema.org/draft/2020-12/schema"
            },
            "type": {
              "const": "object"
            },
            "x-bos-fields": {
              "type": "array"
            }
          }
        },
        "error_contract": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "schema",
            "codes"
          ],
          "properties": {
            "schema": {
              "const": "lead-director-public-error/v1"
            },
            "codes": {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "type": "string",
                "pattern": "^(?:[a-z][a-z0-9_]{0,127}|[A-Z][A-Z0-9_]{0,127})$"
              }
            }
          }
        },
        "sources": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": [
              "source",
              "availability"
            ],
            "properties": {
              "source": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "platform",
                  "application",
                  "plugin"
                ],
                "properties": {
                  "platform": {
                    "type": "string",
                    "minLength": 1
                  },
                  "application": {
                    "type": "string",
                    "minLength": 1
                  },
                  "plugin": {
                    "type": "string",
                    "minLength": 1
                  }
                }
              },
              "availability": {
                "enum": [
                  "ready",
                  "authorization_required",
                  "configuration_required",
                  "temporarily_unavailable",
                  "provider_authorization_required",
                  "source_not_available",
                  "source_temporarily_unavailable"
                ]
              }
            }
          }
        }
      }
    }
  }
};
